<a href="https://colab.research.google.com/github/Nuthana1234/Calibo_assignment_practice/blob/main/calibo_session_21/9/2026-23/9/26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print("Version available is:",pd.__version__)

Version available is: 2.2.3

In [ ]:
import pandas as pd
#print(pd.__version__)
marks = pd.Series([85,90,70,80], name='marks')
print(marks)
student_marks = pd.Series([85,90,95,99,100,53,67,85,76],
                          index = ["Priya","Ravi","Varun","Shyam","Rosy","Sneha","Kavya","Maddie","Sweety"])
print(student_marks)
print("Priya's marks:",student_marks["Priya"])

0    85
1    90
2    70
3    80
Name: marks, dtype: int64
Priya      85
Ravi       90
Varun      95
Shyam      99
Rosy      100
Sneha      53
Kavya      67
Maddie     85
Sweety     76
dtype: int64
Priya's marks: 85

### 🎯 Your Task:
Using **Pandas Series**, perform the following:
✅ Create a Series named `scores` using the dictionary `student_scores`.
✅ Print the marks scored by **"Charlie"** and **"Eva"**.
✅ Add **5 bonus marks** to all students and print the updated Series.
✅ Display only the students who scored **above 90** after the bonus.
✅ Calculate and print the **average marks** of the class (after the bonus).

In [ ]:
import pandas as pd

# Sample dictionary containing student names and their initial scores
student_scores = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 88,
    "Eva": 95
}

# 1. Create a Pandas Series named 'scores'
scores = pd.Series(student_scores)

# 2. Print the marks scored by "Charlie" and "Eva"
print("--- Marks for Charlie and Eva ---")
print(f"Charlie: {scores['Charlie']}")
print(f"Eva: {scores['Eva']}\n")

# 3. Add 5 bonus marks to all students and print the updated Series
scores = scores + 5
print("--- Updated Scores (with +5 Bonus Marks) ---")
print(scores)
print()

# 4. Display only the students who scored above 90 after the bonus
print("--- Students Scoring Above 90 After Bonus ---")
print(scores[scores > 90])
print()

# 5. Calculate and print the average marks of the class
average_marks = scores.mean()
print(f"--- Class Average (After Bonus) ---")
print(f"Average Marks: {average_marks}")

--- Marks for Charlie and Eva ---
Charlie: 78
Eva: 95

--- Updated Scores (with +5 Bonus Marks) ---
Alice       90
Bob         97
Charlie     83
David       93
Eva        100
dtype: int64

--- Students Scoring Above 90 After Bonus ---
Bob       97
David     93
Eva      100
dtype: int64

--- Class Average (After Bonus) ---
Average Marks: 92.6

In [ ]:
import pandas as pd
import numpy as np
data = [
    ["Ravi",21,85],
    ["Priiya",20,92],
    ["Arun",22,76]
]
pd.DataFrame(data, columns=["Name","Age","Marks"])
arr = np.array([[1,80],[2,90],[3,75]])
pd.DataFrame(arr,columns=["Student_ID","marks"])

   Student_ID  marks
0           1     80
1           2     90
2           3     75

In [ ]:
import numpy as np
import pandas as pd

data = ["Ravi", "Prasadi", "Gihan", "Hansana"]

# Fix 1: Wrap the rows inside an outer list to make a proper 2D array
arr = np.array([[25, 85], [25, 90], [26, 70], [24, 80]])

# Fix 2: Correct the spelling of 'columns' and pass them as a list
df = pd.DataFrame(arr, columns=["Age", "Marks"])

# Optional: Add the names as the index so the data aligns
df.index = data

df

         Age  Marks
Ravi      25     85
Prasadi   25     90
Gihan     26     70
Hansana   24     80

In [ ]:
import pandas as pd

a_dict = {
    'name': {'Ru': 'Rukshan', 'Pr': 'Prasadi', 'Gi': 'Gihan', 'Ha': 'Hansana'},
    'age': {'Ru': 25, 'Pr': 25, 'Gi': 26, 'Ha': 24},
    'marks': {'Ru': 85, 'Pr': 90, 'Gi': 70, 'Ha': 80}
}

df = pd.DataFrame(a_dict)
df

       name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
Ha  Hansana   24     80

In [ ]:
import pandas as pd

ser1 = pd.Series(['Rukshan', 'Prasadi', 'Gihan', 'Hansana'], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser2 = pd.Series([25, 25, 26, 24], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser3 = pd.Series([85, 90, 70, 80], index=['Ru', 'Pr', 'Gi', 'Ha'])

a_dict = {
    'name': ser1,
    'age': ser2,
    'marks': ser3
}

df = pd.DataFrame(a_dict)
df

       name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
Ha  Hansana   24     80

🧠 Python Pandas Logical Practice Task
You are given three Series representing student data:
Names of students
Their ages
Their marks
These series are combined into a DataFrame as shown earlier.
🎯 Your Task:
Using the existing DataFrame, perform the following operations:
✅ Print the details (name, age, marks) of the student who scored the highest marks.
✅ Add a new student "Tharushi" with age 23 and marks 88 using the index "Th".
✅ Display the details of students who are 25 years old or older.
✅ Increase the marks of students below 80 by 10 bonus points.
✅ Calculate and print the average marks of all students after the bonus.

In [ ]:
import pandas as pd
name = pd.Series(["Alice","Bob","Charlie","David"])
age = pd.Series([22,21,20,21])
marks = pd.Series([95,98,93,92])
index_labels = pd.Series(["Al","Bb","ch","Dd"])
df = pd.DataFrame({"Name": name, "Age": age, "Marks": marks})
df.index = index_labels
df
highest_student = df.loc[df['Marks'].idxmax()]
print("--- Highest Scoring Student ---")
print(highest_student)
print()
df.loc["Th"] = ["Tharushi", 23, 88]
print("--- DataFrame After Adding Tharushi ---")
print(df)
print()
older_students = df[df['Age'] >= 25]
print("--- Students 25 or Older ---")
print(older_students)
print()
df.loc[df['Marks'] < 80, 'Marks'] += 10
print("--- DataFrame After Applying Bonus ---")
print(df)
print()

# ✅ 5. Calculate and print the average marks after the bonus
average_marks = df['Marks'].mean()
print(f"Average Marks of all students: {average_marks:.2f}")

--- Highest Scoring Student ---
Name     Bob
Age       21
Marks     98
Name: Bb, dtype: object

--- DataFrame After Adding Tharushi ---
        Name  Age  Marks
Al     Alice   22     95
Bb       Bob   21     98
ch   Charlie   20     93
Dd     David   21     92
Th  Tharushi   23     88

--- Students 25 or Older ---
Empty DataFrame
Columns: [Name, Age, Marks]
Index: []

--- DataFrame After Applying Bonus ---
        Name  Age  Marks
Al     Alice   22     95
Bb       Bob   21     98
ch   Charlie   20     93
Dd     David   21     92
Th  Tharushi   23     88

Average Marks of all students: 93.20

Working with dataset

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/Student_Performance.csv")
#displaying first 10 rows in the dataset
df.head(10)

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed

In [ ]:
#to dsiplay last 5 rows
df.tail()

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [ ]:
# to get information regarding the csv dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        61 non-null     int64
 1   Name              61 non-null     object
 2   Age               61 non-null     int64
 3   Gender            61 non-null     object
 4   Department        60 non-null     object
 5   Attendance        59 non-null     float64
 6   Study_Hours       59 non-null     float64
 7   Assignment_Score  61 non-null     int64
 8   Exam_Score        61 non-null     int64
 9   City              61 non-null     object
 10  Enrollment_Date   61 non-null     object
 11  Fee_Status        61 non-null     object
 12  Placement_Status  61 non-null     object
dtypes: float64(2), int64(4), object(7)
memory usage: 6.3+ KB

In [ ]:
# to determine the rows and columns
df.shape

(61, 13)

In [ ]:
df.size

793

In [ ]:
df.describe()

,Student_ID,Age,Attendance,Study_Hours,Assignment_Score,Exam_Score
count,61.000000,61.000000,59.000000,59.000000,61.000000,61.000000
mean,1030.196721,21.688525,86.084746,4.633898,72.688525,80.147541
std,17.479340,1.297960,8.569328,2.084475,15.941080,14.473926
min,1001.000000,20.000000,68.600000,1.500000,45.000000,53.000000
25%,1015.000000,21.000000,79.150000,2.950000,60.000000,70.000000
50%,1030.000000,22.000000,85.100000,4.300000,72.000000,80.000000
75%,1045.000000,23.000000,94.450000,6.300000,84.000000,95.000000
max,1060.000000,24.000000,98.900000,8.400000,98.000000,99.000000

In [ ]:
print("Departments")
print(df["Department"])
print("-------Unique Departments")
print(df["Department"].unique)
print("--------Count of departments----------")
print(df["Department"].value_counts())

Departments
0     Data Science
1            Cloud
2           Python
3     Data Science
4               AI
          ...
56              AI
57              AI
58              AI
59              AI
60           Cloud
Name: Department, Length: 61, dtype: object
-------Unique Departments
<bound method Series.unique of 0     Data Science
1            Cloud
2           Python
3     Data Science
4               AI
          ...
56              AI
57              AI
58              AI
59              AI
60           Cloud
Name: Department, Length: 61, dtype: object>
--------Count of departments----------
Department
AI              25
Data Science    16
Cloud           10
Python           6
 ai              1
data science     1
python           1
Name: count, dtype: int64

In [ ]:
#To print Column Exam_Score
df["Exam_Score"]
df

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [ ]:
# To get 3 columns name,dept,exam-score
df[["Name","Department","Exam_Score"]]
df

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [ ]:
#TO understand label-based indexing
#loc-label based indexing
display(df.loc[0])

Student_ID                   1001
Name                         Ravi
Age                            21
Gender                     Female
Department           Data Science
Attendance                   84.0
Study_Hours                   5.5
Assignment_Score               63
Exam_Score                     78
City                Visakhapatnam
Enrollment_Date        2026-01-05
Fee_Status                   Paid
Placement_Status           Placed
Name: 0, dtype: object

In [ ]:
#To get first person's exam_score
print("Specific value:")
display(df.loc[0,"Exam_Score"])

Specific value:

np.int64(78)

In [ ]:
df.iloc[0:5,0:4]
df

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [ ]:
print("Students with exam score >80:")
display(df[df["Exam_Score"]>80])

Students with exam score >80:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
21,1022,Varun,21,Male,AI,76.8,5.4,89,88,Visakhapatnam,2026-03-09,Pending,Placed
22,1023,Asha,23,Female,AI,77.5,3.6,97,84,Chennai,2026-03-12,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
28,1029,Tarun,21,Male,Data Science,83.3,5.9,73,95,Hyderabad,2026-03-30,Paid,Not Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
33,1034,Mounika,22,Male,Cloud,77.5,7.7,95,99,Bengaluru,2026-04-14,Pending,Not Placed
35,1036,Harini,22,Female,python,83.8,5.6,66,88,Chennai,2026-04-20,Paid,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
43,1044,Sowmya,22,Female,Cloud,78.9,NaN,90,88,Hyderabad,2026-05-14,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [ ]:
print("Students Attendance > 85:")
display(df[df["Attendance"]>85])

Students Attendance > 85:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
12,1013,Kavya,21,Male,Python,95.5,3.0,45,59,Hyderabad,2026-02-10,Paid,Not Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
15,1016,Harish,20,Male,AI,92.3,3.3,78,66,Bengaluru,2026-02-19,Paid,Not Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
19,1020,Rohit,24,Male,AI,97.1,2.5,69,70,Visakhapatnam,2026-03-03,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
32,1033,Pranav,23,Male,AI,90.3,1.9,60,53,Bengaluru,2026-04-11,Paid,Not Placed
36,1037,Ganesh,23,Male,AI,87.7,4.6,73,80,Vijayawada,2026-04-23,Paid,Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
39,1040,Lavanya,23,Female,Data Science,98.3,2.6,49,54,Hyderabad,2026-05-02,Paid,Not Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
44,1045,Surya,23,Female,AI,88.0,1.8,96,80,Bengaluru,2026-05-17,Pending,Not Placed
45,1046,Ishita,23,Male,Python,88.7,3.6,49,69,Visakhapatnam,2026-05-20,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
49,1050,Sravani,20,Female,AI,85.7,3.4,70,70,Hyderabad,2026-06-01,Pending,Not Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [ ]:
print("Students with exam_score >80 and Attendance :85" )
result = df[(df["Exam_Score"]>80) &(df["Attendance"]>85)]
#print(result)
df

Students with exam_score >80 and Attendance :85

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [16]:
print("Highest Exam_Score:")
display(df.sort_values("Exam_Score",ascending = False).head(10))
print("Lowest Attendance:")

Highest Exam_Score:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed

Lowest Attendance:

In [28]:
#Add and modify the problems
#a copy of the csv dataset is made which is stored in work
work = df.copy()
#creating
work["Passed"] = work["Exam_Score"] >= 50
work["Total_Score"] = work["Exam_Score"] + work["Assignment_Score"]
work["Average_Score"] = work[["Total_Score"]].mean(axis=1)
work.head(10)

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,141,141.0
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,160,160.0
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,133.0
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,136.0
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,146.0
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed,True,158,158.0
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed,True,144,144.0
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed,True,188,188.0
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed,True,144,144.0
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed,True,137,137.0

In [32]:
display(work[["Exam_Score","Assignment_Score","Average_Score"]])

    Exam_Score  Assignment_Score  Average_Score
0           78                63          141.0
1           99                61          160.0
2           70                63          133.0
3           64                72          136.0
4           76                70          146.0
..         ...               ...            ...
56          64                81          145.0
57          56                67          123.0
58          99                54          153.0
59          99                98          197.0
60          73                97          170.0

[61 rows x 3 columns]

In [34]:
#Feature Engineering
import numpy as np
work["Performance_Level"] = np.where(
    work["Exam_Score"] >= 85,"Excellent",
    np.where(work["Exam_Score"] >= 70,"Good","Needs Improvement")

)
display(work[["Name","Performance_Level"]].head(10))

        Name  Performance_Level
0       Ravi               Good
1      Priya          Excellent
2       Arun               Good
3      Meena  Needs Improvement
4      Kiran               Good
5     Suresh               Good
6     Anjali               Good
7      Rahul          Excellent
8      Divya               Good
9    Rahul                 Good

In [36]:
renamed = df.rename(columns={
    "Exam_Score": "Final_Exam_Score",
    "Study_Hours":"Daily_Study_Hours"
})
renamed.head()

,Student_ID,Name,Age,Gender,Department,Attendance,Daily_Study_Hours,Assignment_Score,Final_Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed

In [38]:
example = work.drop(columns = "Total_Score")
example.head()

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Average_Score,Performance_Level
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,141.0,Good
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,160.0,Excellent
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133.0,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136.0,Needs Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146.0,Good

In [39]:
df

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [40]:
work

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score,Performance_Level
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,141,141.0,Good
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,160,160.0,Excellent
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,133.0,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,136.0,Needs Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,146.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed,True,145,145.0,Needs Improvement
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed,True,123,123.0,Needs Improvement
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed,True,153,153.0,Excellent
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed,True,197,197.0,Excellent
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed,True,170,170.0,Good

In [44]:
example1 = work.drop([0,1])
example1.head()

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score,Performance_Level
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,133.0,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,136.0,Needs Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,146.0,Good
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed,True,158,158.0,Good
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed,True,144,144.0,Good

In [45]:
print("How many missing values by column")
display(df.isna().sum())

How many missing values by column

Student_ID          0
Name                0
Age                 0
Gender              0
Department          1
Attendance          2
Study_Hours         2
Assignment_Score    0
Exam_Score          0
City                0
Enrollment_Date     0
Fee_Status          0
Placement_Status    0
dtype: int64

In [52]:
display(df.isna().sum().sum())
df.shape

np.int64(5)

(61, 13)

In [56]:
complete = df.dropna().sum()
complete.shape

(13,)

In [55]:
complete.head()

Student_ID                                                57693
Name          RaviPriyaArunMeenaSureshAnjaliRahulDivya  Rahu...
Age                                                        1212
Gender        FemaleMaleFemaleMaleFemaleFemaleMaleFemaleFema...
Department    Data ScienceCloudPythonData ScienceAIAI ai Dat...
dtype: object

In [60]:
filled = df.copy()
filled["Attendance"] = filled["Attendance"].fillna(
    filled["Attendance"].median()
    )
filled["Study_Hours"] = filled["Study_Hours"].fillna(
    filled["Study_Hours"].median()
)
filled["Department"] = filled["Department"].fillna("Unknown")
print("Remaining missing values:")
print(filled.isna().sum())

Remaining missing values:
Student_ID          0
Name                0
Age                 0
Gender              0
Department          0
Attendance          0
Study_Hours         0
Assignment_Score    0
Exam_Score          0
City                0
Enrollment_Date     0
Fee_Status          0
Placement_Status    0
dtype: int64

Duplicates identification and removal

In [68]:
print("Duplicate rows:",df.duplicated().sum())
print("Duplicate record:")
display(df[df.duplicated(keep = False)])
df_no_duplicate = df.drop_duplicates()
print("Shape after removing duplicates",df_no_duplicate.shape)

Duplicate rows: 1
Duplicate record:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
11,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

Shape after removing duplicates (60, 13)

**Any Columns contains strings**

In [74]:
names = pd.Series(["rama ","Priya "," Radhika"," Hasini"])
print("Clean Spaces")
print(names.str.strip())
print("Lowercase")
print(names.str.lower())
print("Upper Case")
print(names.str.upper())
print("Title Case")
print(names.str.title())

Clean Spaces
0       rama
1      Priya
2    Radhika
3     Hasini
dtype: object
Lowercase
0       rama
1      priya
2     radhika
3      hasini
dtype: object
Upper Case
0       RAMA
1      PRIYA
2     RADHIKA
3      HASINI
dtype: object
Title Case
0       Rama
1      Priya
2     Radhika
3      Hasini
dtype: object

In [76]:
df.dtypes

Student_ID            int64
Name                 object
Age                   int64
Gender               object
Department           object
Attendance          float64
Study_Hours         float64
Assignment_Score      int64
Exam_Score            int64
City                 object
Enrollment_Date      object
Fee_Status           object
Placement_Status     object
dtype: object

In [77]:
demo = pd.DataFrame({
    "Marks":["80","92","Invalid","75"]
})
demo["Marks"] = pd.to_numeric(demo["Marks"],errors = "coerce")
print(demo)
demo.dtypes

   Marks
0   80.0
1   92.0
2    NaN
3   75.0

Marks    float64
dtype: object

groupby()

In [80]:
clean = df.copy()
dept_avg = (
    clean.groupby("Department")["Exam_Score"]
    .mean()
    .sort_values(ascending = False)
)
dept_avg

Department
 ai             91.000000
python          88.000000
Cloud           87.900000
data science    82.000000
AI              79.320000
Python          77.333333
Data Science    76.562500
Name: Exam_Score, dtype: float64

In [81]:
clean = df.copy()
dept_avg = (
    clean.groupby("Department")["Exam_Score"]
    .agg(["count","mean","min","max"])
    .round(2)
)
dept_avg

              count   mean  min  max
Department
 ai               1  91.00   91   91
AI               25  79.32   53   99
Cloud            10  87.90   72   99
Data Science     16  76.56   54   99
Python            6  77.33   59   98
data science      1  82.00   82   82
python            1  88.00   88   88