<a href="https://colab.research.google.com/github/Nuthana1234/Calibo_assignment_practice/blob/main/calibo_session_21_9_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import pandas as pd
print("Version available is:",pd.__version__)

Version available is: 2.2.3

In [13]:
import pandas as pd
#print(pd.__version__)
marks = pd.Series([85,90,70,80], name='marks')
print(marks)
student_marks = pd.Series([85,90,95,99,100,53,67,85,76],
                          index = ["Priya","Ravi","Varun","Shyam","Rosy","Sneha","Kavya","Maddie","Sweety"])
print(student_marks)
print("Priya's marks:",student_marks["Priya"])

0    85
1    90
2    70
3    80
Name: marks, dtype: int64
Priya      85
Ravi       90
Varun      95
Shyam      99
Rosy      100
Sneha      53
Kavya      67
Maddie     85
Sweety     76
dtype: int64
Priya's marks: 85

### 🎯 Your Task:
Using **Pandas Series**, perform the following:
✅ Create a Series named `scores` using the dictionary `student_scores`.
✅ Print the marks scored by **"Charlie"** and **"Eva"**.
✅ Add **5 bonus marks** to all students and print the updated Series.
✅ Display only the students who scored **above 90** after the bonus.
✅ Calculate and print the **average marks** of the class (after the bonus).

In [26]:
import pandas as pd

# Sample dictionary containing student names and their initial scores
student_scores = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 88,
    "Eva": 95
}

# 1. Create a Pandas Series named 'scores'
scores = pd.Series(student_scores)

# 2. Print the marks scored by "Charlie" and "Eva"
print("--- Marks for Charlie and Eva ---")
print(f"Charlie: {scores['Charlie']}")
print(f"Eva: {scores['Eva']}\n")

# 3. Add 5 bonus marks to all students and print the updated Series
scores = scores + 5
print("--- Updated Scores (with +5 Bonus Marks) ---")
print(scores)
print()

# 4. Display only the students who scored above 90 after the bonus
print("--- Students Scoring Above 90 After Bonus ---")
print(scores[scores > 90])
print()

# 5. Calculate and print the average marks of the class
average_marks = scores.mean()
print(f"--- Class Average (After Bonus) ---")
print(f"Average Marks: {average_marks}")

--- Marks for Charlie and Eva ---
Charlie: 78
Eva: 95

--- Updated Scores (with +5 Bonus Marks) ---
Alice       90
Bob         97
Charlie     83
David       93
Eva        100
dtype: int64

--- Students Scoring Above 90 After Bonus ---
Bob       97
David     93
Eva      100
dtype: int64

--- Class Average (After Bonus) ---
Average Marks: 92.6

In [28]:
import pandas as pd
import numpy as np
data = [
    ["Ravi",21,85],
    ["Priiya",20,92],
    ["Arun",22,76]
]
pd.DataFrame(data, columns=["Name","Age","Marks"])
arr = np.array([[1,80],[2,90],[3,75]])
pd.DataFrame(arr,columns=["Student_ID","marks"])

   Student_ID  marks
0           1     80
1           2     90
2           3     75

In [38]:
import numpy as np
import pandas as pd

data = ["Ravi", "Prasadi", "Gihan", "Hansana"]

# Fix 1: Wrap the rows inside an outer list to make a proper 2D array
arr = np.array([[25, 85], [25, 90], [26, 70], [24, 80]])

# Fix 2: Correct the spelling of 'columns' and pass them as a list
df = pd.DataFrame(arr, columns=["Age", "Marks"])

# Optional: Add the names as the index so the data aligns
df.index = data

df

         Age  Marks
Ravi      25     85
Prasadi   25     90
Gihan     26     70
Hansana   24     80

In [37]:
import pandas as pd

a_dict = {
    'name': {'Ru': 'Rukshan', 'Pr': 'Prasadi', 'Gi': 'Gihan', 'Ha': 'Hansana'},
    'age': {'Ru': 25, 'Pr': 25, 'Gi': 26, 'Ha': 24},
    'marks': {'Ru': 85, 'Pr': 90, 'Gi': 70, 'Ha': 80}
}

df = pd.DataFrame(a_dict)
df

       name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
Ha  Hansana   24     80

In [41]:
import pandas as pd

ser1 = pd.Series(['Rukshan', 'Prasadi', 'Gihan', 'Hansana'], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser2 = pd.Series([25, 25, 26, 24], index=['Ru', 'Pr', 'Gi', 'Ha'])
ser3 = pd.Series([85, 90, 70, 80], index=['Ru', 'Pr', 'Gi', 'Ha'])

a_dict = {
    'name': ser1,
    'age': ser2,
    'marks': ser3
}

df = pd.DataFrame(a_dict)
df

       name  age  marks
Ru  Rukshan   25     85
Pr  Prasadi   25     90
Gi    Gihan   26     70
Ha  Hansana   24     80

🧠 Python Pandas Logical Practice Task
You are given three Series representing student data:
Names of students
Their ages
Their marks
These series are combined into a DataFrame as shown earlier.
🎯 Your Task:
Using the existing DataFrame, perform the following operations:
✅ Print the details (name, age, marks) of the student who scored the highest marks.
✅ Add a new student "Tharushi" with age 23 and marks 88 using the index "Th".
✅ Display the details of students who are 25 years old or older.
✅ Increase the marks of students below 80 by 10 bonus points.
✅ Calculate and print the average marks of all students after the bonus.

In [46]:
import pandas as pd
name = pd.Series(["Alice","Bob","Charlie","David"])
age = pd.Series([22,21,20,21])
marks = pd.Series([95,98,93,92])
index_labels = pd.Series(["Al","Bb","ch","Dd"])
df = pd.DataFrame({"Name": name, "Age": age, "Marks": marks})
df.index = index_labels
df
highest_student = df.loc[df['Marks'].idxmax()]
print("--- Highest Scoring Student ---")
print(highest_student)
print()
df.loc["Th"] = ["Tharushi", 23, 88]
print("--- DataFrame After Adding Tharushi ---")
print(df)
print()
older_students = df[df['Age'] >= 25]
print("--- Students 25 or Older ---")
print(older_students)
print()
df.loc[df['Marks'] < 80, 'Marks'] += 10
print("--- DataFrame After Applying Bonus ---")
print(df)
print()

# ✅ 5. Calculate and print the average marks after the bonus
average_marks = df['Marks'].mean()
print(f"Average Marks of all students: {average_marks:.2f}")

--- Highest Scoring Student ---
Name     Bob
Age       21
Marks     98
Name: Bb, dtype: object

--- DataFrame After Adding Tharushi ---
        Name  Age  Marks
Al     Alice   22     95
Bb       Bob   21     98
ch   Charlie   20     93
Dd     David   21     92
Th  Tharushi   23     88

--- Students 25 or Older ---
Empty DataFrame
Columns: [Name, Age, Marks]
Index: []

--- DataFrame After Applying Bonus ---
        Name  Age  Marks
Al     Alice   22     95
Bb       Bob   21     98
ch   Charlie   20     93
Dd     David   21     92
Th  Tharushi   23     88

Average Marks of all students: 93.20

Working with dataset

In [59]:
import numpy as np
import pandas as pd
df = pd.read_csv("/content/Student_Performance.csv")
#displaying first 10 rows in the dataset
df.head(10)

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed

In [60]:
#to dsiplay last 5 rows
df.tail()

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [61]:
# to get information regarding the csv dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        61 non-null     int64
 1   Name              61 non-null     object
 2   Age               61 non-null     int64
 3   Gender            61 non-null     object
 4   Department        60 non-null     object
 5   Attendance        59 non-null     float64
 6   Study_Hours       59 non-null     float64
 7   Assignment_Score  61 non-null     int64
 8   Exam_Score        61 non-null     int64
 9   City              61 non-null     object
 10  Enrollment_Date   61 non-null     object
 11  Fee_Status        61 non-null     object
 12  Placement_Status  61 non-null     object
dtypes: float64(2), int64(4), object(7)
memory usage: 6.3+ KB

In [63]:
# to determine the rows and columns
df.shape

(61, 13)

In [64]:
df.size

793

In [67]:
df.describe()

,Student_ID,Age,Attendance,Study_Hours,Assignment_Score,Exam_Score
count,61.000000,61.000000,59.000000,59.000000,61.000000,61.000000
mean,1030.196721,21.688525,86.084746,4.633898,72.688525,80.147541
std,17.479340,1.297960,8.569328,2.084475,15.941080,14.473926
min,1001.000000,20.000000,68.600000,1.500000,45.000000,53.000000
25%,1015.000000,21.000000,79.150000,2.950000,60.000000,70.000000
50%,1030.000000,22.000000,85.100000,4.300000,72.000000,80.000000
75%,1045.000000,23.000000,94.450000,6.300000,84.000000,95.000000
max,1060.000000,24.000000,98.900000,8.400000,98.000000,99.000000

In [76]:
print("Departments")
print(df["Department"])
print("-------Unique Departments")
print(df["Department"].unique)
print("--------Count of departments----------")
print(df["Department"].value_counts())

Departments
0     Data Science
1            Cloud
2           Python
3     Data Science
4               AI
          ...
56              AI
57              AI
58              AI
59              AI
60           Cloud
Name: Department, Length: 61, dtype: object
-------Unique Departments
<bound method Series.unique of 0     Data Science
1            Cloud
2           Python
3     Data Science
4               AI
          ...
56              AI
57              AI
58              AI
59              AI
60           Cloud
Name: Department, Length: 61, dtype: object>
--------Count of departments----------
Department
AI              25
Data Science    16
Cloud           10
Python           6
 ai              1
data science     1
python           1
Name: count, dtype: int64

In [78]:
#To print Column Exam_Score
df["Exam_Score"]
df

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [84]:
# To get 3 columns name,dept,exam-score
df[["Name","Department","Exam_Score"]]
df

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [87]:
#TO understand label-based indexing
#loc-label based indexing
display(df.loc[0])

Student_ID                   1001
Name                         Ravi
Age                            21
Gender                     Female
Department           Data Science
Attendance                   84.0
Study_Hours                   5.5
Assignment_Score               63
Exam_Score                     78
City                Visakhapatnam
Enrollment_Date        2026-01-05
Fee_Status                   Paid
Placement_Status           Placed
Name: 0, dtype: object

In [95]:
#To get first person's exam_score
print("Specific value:")
display(df.loc[0,"Exam_Score"])

Specific value:

np.int64(78)